
config_dir: "/home/nlahaye/fire_spread_compare/configs/fperim/"

fname: "/home/nlahaye/Fire_Fronts/feds_western_us_2020_af_postprocessed.parquet"

fstart: 1
fcompare: 2
mergeid: 69497

resolution_deg: 0.0027


output_field: "flame-length"
model_dir: "glass_2/pyretechnics-deck"

percentiles: [10,20,30,40,50,60,70,80,90,99]

fire_name: "glass_step_2"
output_dir: "/home/nlahaye/fire_spread_compare/fcomp/"
compare_tint: "012"



