

config_dir: "/home/nlahaye/fire_spread_compare/configs/fperim/"

time: "2020-09-28T00:00:00"
FRAPfnm: "GLASS_STEP_2" #"CREEK"
fname: "/home/nlahaye/Fire_Fronts/feds_western_us_2020_af_postprocessed.parquet"

fstart: 1
mergeid: 69497





